### ISSUE TITLE
Problem setting 0 as subnet mask

### ISSUE THREAD

**Issue by nowimhere** [AndiSHFR/wake-on-lan.php#2]
Hi and thank you 4 this tool!
Could you tell me if it is possibile to send to 0.0.0.0 (see the attach) 
If i set a network broadcast 0 the program crashes...

Thank you

**Comment by nowimhere** [comment]
![im](https://user-images.githubusercontent.com/17923351/76678538-2453c600-65d9-11ea-92a7-837212a5687d.jpg)

**Comment by AndiSHFR** [comment]
I just did a test with cidr set to 0 and there was no crash. Can so add php logs or a screenshot showing the crash?

![image](https://user-images.githubusercontent.com/515262/77767593-9bf60c00-7041-11ea-9fc4-451d95109320.png)
