### ISSUE TITLE
PHP 8.2 Warning

### ISSUE THREAD

**Issue by righter83** [AndiSHFR/wake-on-lan.php#23]
Hi 

I upgrade from Debian 11 to 12, evertyhing is still working but I got a lot of such messages:
`PHP Warning:  {closure}(): Argument #2 ($key) must be passed by reference, value given in /var/www/wol/wake-on-lan.php on line 200`

referenced to this codeblock (array_walk is line 200):
`function endWithJsonResponse($responseData, $filename = NULL) {
  if($responseData) {
    array_walk_recursive($responseData, function(&$value, &$key) {
      if(is_string($value)) $value = iso8859_1_to_utf8($value);
    });  
  }
`

**Comment by righter83** [comment]
I was able to fix it

change:
`    array_walk_recursive($responseData, function(&$value, &$key) {`

to 
`    array_walk_recursive($responseData, function($value, $key) {
`

**Comment by idunwannagotoschool** [comment]
can @AndiSHFR commit the fix please?
