### ISSUE TITLE
Working on Ubuntu 20.04

### ISSUE THREAD

**Issue by drewmw5** [AndiSHFR/wake-on-lan.php#4]
The readme states that this does not run under linux, but I was able to get this functioning perfectly fine. The only necessary step is to uncomment the sockets extension located in /etc/php/7.4/apache2/php.ini. 

extensions=sockets

It worked immediately after uncommenting that line. 

Hope that might help someone.

**Comment by AndiSHFR** [comment]
Great tip. I tested this on MacOS with XAMPP and it looks really good. 
Lets see if i can spend some time changing the code from fopen() to socket_xxx().
Basically there is already code for doing this but it needs some cleanup! ;)

Big thanks to you - drewmw5!

**Comment by AndiSHFR** [comment]
Closing this issue as the current version solely relies on php_socket() functionality.
