### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by giuseppe-modugno** [AndiSHFR/wake-on-lan.php#5]
I copied your PHP script on QNAP Web folder. I can really see the page pointing to /wake-on-lan.php, but I receive the error specified in the subject "Permission Denied". Why? Isn't the user running the PHP server authorized to create raw packets?

**Comment by AndiSHFR** [comment]
Hi Giuseppe, i got some questions:

* Is "Permission Denied" the exact message?
* Could you post a screenshot of the page showing the error message?
* What version of PHP is running o the QNAP?

**Comment by AndiSHFR** [comment]
I found a note in a qnap forum under the subject "PING from PHP application" and there you can find the following comment:

> ...
> RAW sockets are restricted to root accounts and the web server is running as httpdusr.
> ...
> 

Also there is a discussion that the application (i assume the php file?) must be setuid root to be able to open raw socket.

Hope this helps to solve your issue.

Link to QNAP community forum: [PING from PHP application](https://forum.qnap.com/viewtopic.php?p=146628)

**Comment by giuseppe-modugno** [comment]
I suspected something similar. Anyway I think it's better to run PHP web server without root privileges, so this should be a common problem.
I think the best solution is calling a setuid root _external_ application, such as ping, from the PHP script and decode the output or the return code.
Your approach is different, because you create ping packets from low level so you need root privileges.

**Comment by AndiSHFR** [comment]
You are absolutely right. My approach was focused on a "one file" drop in solution.
Maybe if the QNAP applicance has a wake-on-lan application built in it might be possible to comment the php code and call the qnap app instead.

Quick search: [wake up client...](https://forum.qnap.com/viewtopic.php?t=98276) 

> /opt/bin/wakelan -h
> Usage: wakelan [options] [mac] [broadcast] [port]
>     -b addr    broadcast address
>     -m mac     mac address of host
>     -p port    UDP port to broadcast to
>     -v[v]      version


My function signature look like: 

> function wakeOnLan($mac, $ip, $cidr, $port, &$debugOut) 

So basically this should be possible. Maybe like this kind of code at line #28

> exec('/opt/bin/wakelan -m ' . $mac . ' -p ' . $port .  ' -b ...broadcast here... ', $wolResult);
> return $wolResult;

Well... not that easy. As i'm loking at the code i would tend to add another function w/ same signature and limit code to creating broadcast address from the $ip and $cidr and executing wakelan app. Then use this function if there is a file "/opt/bin/wakelan" available. :)

Do you have any coding experience?

**Comment by giuseppe-modugno** [comment]
Yes I have /opt/bin/wakelan, indeed I currently wake up PCs with this application.

I have some coding experience, but not in PHP. Maybe you can change your code such that it will call an external application, if exist, or create a WOL packet itself.

**Comment by klemens-st** [comment]
@giuseppe-modugno I have just deployed this on a Ubuntu server in a small office internal network. I have rewritten the code to use the 'wakeonlan' command which is similar to 'wakelan'. If you are interested I can clean up my code (yes, it's a mess done in a hurry 😁) and upload it so you can work out your way from there.
