### ISSUE TITLE
×Error 200 calling "GET ?op=wol":OK

### ISSUE THREAD

**Issue by FrankG203** [AndiSHFR/wake-on-lan.php#6]
Hello,
i have installed the Wakeonlan php on a Windows 10 Xamppp new installation.
When i now start the wakeonlan tool and klick to wakeup comes this message:
×Error 200 calling "GET ?op=wol":OK

Thx for your help.

Frank

**Comment by ignore-me-now** [comment]
Same here, try Xampp with PHP 7 and 8, same happend. 
Someone can help?
It looks like the script i really wait for years... :)

**Comment by AndiSHFR** [comment]
Sorry for the inconvenience. Please download and use the current version and give it a try.
It is a whole rework and addresses a lot of issues around the raw sockets and some other things.

Please see the README about things that have changed.

This version already runs on a users raspberry pi (thanks to Andreas from Austria for the valuable help as an beta tester).
